// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: finalcache.proto

package finalcachepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FinalCache service

func NewFinalCacheEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FinalCache service

type FinalCacheService interface {
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...client.CallOption) (*SetResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...client.CallOption) (*DelResponse, error)
}

type finalCacheService struct {
	c    client.Client
	name string
}

func NewFinalCacheService(name string, c client.Client) FinalCacheService {
	return &finalCacheService{
		c:    c,
		name: name,
	}
}

func (c *finalCacheService) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "FinalCache.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finalCacheService) Set(ctx context.Context, in *SetRequest, opts ...client.CallOption) (*SetResponse, error) {
	req := c.c.NewRequest(c.name, "FinalCache.Set", in)
	out := new(SetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finalCacheService) Del(ctx context.Context, in *DelRequest, opts ...client.CallOption) (*DelResponse, error) {
	req := c.c.NewRequest(c.name, "FinalCache.Del", in)
	out := new(DelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FinalCache service

type FinalCacheHandler interface {
	Get(context.Context, *GetRequest, *GetResponse) error
	Set(context.Context, *SetRequest, *SetResponse) error
	Del(context.Context, *DelRequest, *DelResponse) error
}

func RegisterFinalCacheHandler(s server.Server, hdlr FinalCacheHandler, opts ...server.HandlerOption) error {
	type finalCache interface {
		Get(ctx context.Context, in *GetRequest, out *GetResponse) error
		Set(ctx context.Context, in *SetRequest, out *SetResponse) error
		Del(ctx context.Context, in *DelRequest, out *DelResponse) error
	}
	type FinalCache struct {
		finalCache
	}
	h := &finalCacheHandler{hdlr}
	return s.Handle(s.NewHandler(&FinalCache{h}, opts...))
}

type finalCacheHandler struct {
	FinalCacheHandler
}

func (h *finalCacheHandler) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.FinalCacheHandler.Get(ctx, in, out)
}

func (h *finalCacheHandler) Set(ctx context.Context, in *SetRequest, out *SetResponse) error {
	return h.FinalCacheHandler.Set(ctx, in, out)
}

func (h *finalCacheHandler) Del(ctx context.Context, in *DelRequest, out *DelResponse) error {
	return h.FinalCacheHandler.Del(ctx, in, out)
}
