// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finalcache.proto

package finalcachepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  int32    `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	IsHotKey             bool     `protobuf:"varint,4,opt,name=is_hot_key,json=isHotKey,proto3" json:"is_hot_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResponse) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *GetResponse) GetIsHotKey() bool {
	if m != nil {
		return m.IsHotKey
	}
	return false
}

type SetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  int32    `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{3}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SetRequest) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type SetResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{4}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type DelRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{5}
}

func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (m *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(m, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResponse) Reset()         { *m = DelResponse{} }
func (m *DelResponse) String() string { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()    {}
func (*DelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d88bb3942ef4fba, []int{6}
}

func (m *DelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResponse.Unmarshal(m, b)
}
func (m *DelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResponse.Marshal(b, m, deterministic)
}
func (m *DelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResponse.Merge(m, src)
}
func (m *DelResponse) XXX_Size() int {
	return xxx_messageInfo_DelResponse.Size(m)
}
func (m *DelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelResponse proto.InternalMessageInfo

func (m *DelResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "finalcachepb.Result")
	proto.RegisterType((*GetRequest)(nil), "finalcachepb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "finalcachepb.GetResponse")
	proto.RegisterType((*SetRequest)(nil), "finalcachepb.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "finalcachepb.SetResponse")
	proto.RegisterType((*DelRequest)(nil), "finalcachepb.DelRequest")
	proto.RegisterType((*DelResponse)(nil), "finalcachepb.DelResponse")
}

func init() {
	proto.RegisterFile("finalcache.proto", fileDescriptor_8d88bb3942ef4fba)
}

var fileDescriptor_8d88bb3942ef4fba = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x53, 0x07, 0x0b, 0xbc, 0x11, 0x43, 0x1a, 0x0e, 0xd3, 0x18, 0xb3, 0xf4, 0xb4, 0x83,
	0xd9, 0x01, 0x6f, 0x70, 0x53, 0x02, 0x26, 0xde, 0xda, 0x9b, 0x17, 0x32, 0xe6, 0x53, 0x16, 0x2b,
	0x9d, 0xb4, 0x33, 0xe1, 0xe8, 0x7f, 0xe6, 0x9f, 0x66, 0x5a, 0x48, 0xc6, 0x50, 0x0c, 0xd9, 0xed,
	0xdb, 0xbe, 0xf7, 0xf5, 0xd7, 0xf7, 0xfa, 0xa0, 0xff, 0x92, 0xaf, 0x52, 0x99, 0xa5, 0xd9, 0x12,
	0x93, 0x62, 0xad, 0x8c, 0xa2, 0xbd, 0xea, 0x4f, 0xb1, 0x60, 0x09, 0xf8, 0x1c, 0x75, 0x29, 0x0d,
	0xa5, 0xd0, 0xca, 0xd4, 0x33, 0x86, 0x24, 0x22, 0x71, 0x9b, 0x3b, 0x4d, 0xfb, 0xe0, 0xbd, 0xeb,
	0xd7, 0xf0, 0x2c, 0x22, 0x71, 0x97, 0x5b, 0xc9, 0xae, 0x01, 0x66, 0x68, 0x38, 0x7e, 0x94, 0xa8,
	0x8d, 0xf5, 0xdf, 0x70, 0xe3, 0x22, 0x5d, 0x6e, 0x25, 0xfb, 0x22, 0x10, 0xb8, 0x02, 0x5d, 0xa8,
	0x95, 0x46, 0x7a, 0x03, 0xfe, 0xda, 0x9d, 0xef, 0x8a, 0x82, 0xe1, 0x20, 0xd9, 0xc7, 0x27, 0x5b,
	0x36, 0xdf, 0xd5, 0xd0, 0x01, 0xb4, 0x3f, 0x53, 0x59, 0xa2, 0x23, 0xf6, 0xf8, 0xf6, 0xc3, 0x52,
	0x8c, 0x91, 0xa1, 0xe7, 0x2e, 0x66, 0x25, 0xbd, 0x02, 0xc8, 0xf5, 0x7c, 0xa9, 0xcc, 0xdc, 0xe2,
	0x5b, 0x11, 0x89, 0x3b, 0xbc, 0x93, 0xeb, 0x07, 0x65, 0x1e, 0x71, 0xc3, 0xa6, 0x00, 0xe2, 0x9f,
	0x3b, 0x9e, 0x4a, 0x61, 0x63, 0x08, 0x44, 0xd3, 0x56, 0xec, 0xa0, 0x26, 0x28, 0x8f, 0x0f, 0x6a,
	0x0c, 0x81, 0xf3, 0x9b, 0x1c, 0x3e, 0xfc, 0x26, 0x00, 0x53, 0xeb, 0xdf, 0x5b, 0x9f, 0x8e, 0xc0,
	0x9b, 0xa1, 0xa1, 0x61, 0x3d, 0x53, 0xbd, 0xd3, 0xe5, 0xc5, 0x1f, 0xce, 0x0e, 0x3c, 0x02, 0x4f,
	0xfc, 0xce, 0x8a, 0xa3, 0x59, 0x51, 0xcf, 0x4e, 0x50, 0x1e, 0x66, 0xab, 0xb6, 0x0f, 0xb3, 0x7b,
	0x0d, 0xdf, 0x9d, 0x3f, 0xd5, 0x16, 0x71, 0xe1, 0xbb, 0xed, 0xbc, 0xfd, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x4b, 0x8d, 0x2e, 0xb1, 0x02, 0x00, 0x00,
}
